version: '3'

services:
  db:
    image: postgres:latest
    container_name: catalog-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
