name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Download CodeClimate test reporter
      run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        
    - name: Give permissions to CodeClimate test reporter
      run: chmod +x ./cc-test-reporter

    - name: Execute CodeClimate test reporter before build
      run: ./cc-test-reporter before-build

    - name: Install dependencies
      run: npm install

    - name: Execute linting
      run: npm run lint

    - name: Execute types checking
      run: npm run types:check

    - name: Build project
      run: npm run build --if-present

    - name: Execute tests
      run: npm run test:cov

    - name: Format CodeCLimate test results
      run: ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info

    - name: Upload CodeClimate test results
      run: ./cc-test-reporter upload-coverage
